// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// interrupt-gams-win.cpp
int windowsInterruptGAMS(int pid);
extern "C" SEXP _miroUtil_windowsInterruptGAMS(SEXP pid) {
  BEGIN_CPP11
    return cpp11::as_sexp(windowsInterruptGAMS(cpp11::as_cpp<cpp11::decay_t<int>>(pid)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_miroUtil_windowsInterruptGAMS", (DL_FUNC) &_miroUtil_windowsInterruptGAMS, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_miroUtil(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
